# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6343e6c7bf4025470108b8d927f25512b62f1c88c250deb837d1699a0ffcdd67cf2b5583dadb36ae6681c9955624cb143d376da32bc7eb788799349eaa5de4e9

test:
  secret_key_base: e9e0938804b9554b5e27ca65434f0b8a1b05b57d1cdf547e9927006b2ab8ff766763df3a7008dc36ccea97bc06eb25ea550087201018c0bdfd3a26f52a84d486

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
